name: yugioh
description: "Prueba Isaac Sanchez"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  phosphor_flutter: ^2.0.1
  page_transition: ^2.0.9
  flutter_spinkit: ^5.2.0
  animate_do: ^3.1.2
  shared_preferences: ^2.2.1
  http: ^1.1.0
  intl: ^0.18.0
  provider: ^6.0.5
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:



  uses-material-design: true



  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
